# Generated by Django 5.2 on 2025-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_explorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsong',
            name='track_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savedsong',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
